on: push
    
jobs:
    docker:
        runs-on: ubuntu-latest 
        steps:
        - uses: actions/checkout@main
        - run: |
              git clone https://chaowenguo@bitbucket.org/chaowenguo/pal
              cd pal
              git push -f https://chaowenguo:HL798820y+@github.com/0orgchaowenguo/pal
